//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessageErro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessageErro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exception.ResourceMessageErro", typeof(ResourceMessageErro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Corrente precisa ser informada.
        /// </summary>
        public static string CURRENT_TRANSFORMER_EMPTY {
            get {
                return ResourceManager.GetString("CURRENT_TRANSFORMER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail do usuário deve ser informado..
        /// </summary>
        public static string EMAIL_USER_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_USER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail do usuário deve ser válido.
        /// </summary>
        public static string EMAIL_USER_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_USER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro Desconhecido..
        /// </summary>
        public static string ERRO_UNKNOWN {
            get {
                return ResourceManager.GetString("ERRO_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os ID&apos;s informados não são iguais.
        /// </summary>
        public static string ID_NOT_THE_SAME {
            get {
                return ResourceManager.GetString("ID_NOT_THE_SAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do teste precisa ser informado.
        /// </summary>
        public static string ID_TEST_EMPTY {
            get {
                return ResourceManager.GetString("ID_TEST_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do transformador precisa ser informado.
        /// </summary>
        public static string ID_TRANSFORMER_EMPTY {
            get {
                return ResourceManager.GetString("ID_TRANSFORMER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do usuário precisa ser informado.
        /// </summary>
        public static string ID_USER_TRANSFORMER_EMPTY {
            get {
                return ResourceManager.GetString("ID_USER_TRANSFORMER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do transformador precisa ser informado.
        /// </summary>
        public static string NAME_TRANSFORMER_EMPTY {
            get {
                return ResourceManager.GetString("NAME_TRANSFORMER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário deve ser informado..
        /// </summary>
        public static string NAME_USER_EMPTY {
            get {
                return ResourceManager.GetString("NAME_USER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem registro na base de dados.
        /// </summary>
        public static string NOT_FOUND {
            get {
                return ResourceManager.GetString("NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O numero interno precisa ser informado.
        /// </summary>
        public static string NUMBER_TRANSFORMER_EMPTY {
            get {
                return ResourceManager.GetString("NUMBER_TRANSFORMER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter pelo menos 6 caracteres.
        /// </summary>
        public static string PASSWORD_MIN_SIX_CHARACTERS {
            get {
                return ResourceManager.GetString("PASSWORD_MIN_SIX_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha do usuário deve ser informado..
        /// </summary>
        public static string PASSWORD_USER_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_USER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Potência precisa ser informada .
        /// </summary>
        public static string POTENCY_TRANSFORMER_EMPTY {
            get {
                return ResourceManager.GetString("POTENCY_TRANSFORMER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatório deletado com sucesso.
        /// </summary>
        public static string REPORT_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("REPORT_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao tentar deletar o relatório.
        /// </summary>
        public static string REPORT_FAIL_DELETE {
            get {
                return ResourceManager.GetString("REPORT_FAIL_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RELATORIO POR ID EXISTE.
        /// </summary>
        public static string REPORT_ID_EXIST {
            get {
                return ResourceManager.GetString("REPORT_ID_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe relatório com esse ID na base de dados.
        /// </summary>
        public static string REPORT_ID_NOT_FOUND {
            get {
                return ResourceManager.GetString("REPORT_ID_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário deve ser informado..
        /// </summary>
        public static string TELEPHONE_USER_EMPTY {
            get {
                return ResourceManager.GetString("TELEPHONE_USER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Telefone do usuário deve ser válido.
        /// </summary>
        public static string TELEPHONE_USER_INVALID {
            get {
                return ResourceManager.GetString("TELEPHONE_USER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tensão precisa ser informada.
        /// </summary>
        public static string TENSION_CLASS_TRANSFORMER_EMPTY {
            get {
                return ResourceManager.GetString("TENSION_CLASS_TRANSFORMER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teste deletado com sucesso.
        /// </summary>
        public static string TEST_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("TEST_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A duração em segundos precisa ser informada.
        /// </summary>
        public static string TEST_DURATION_EMPTY {
            get {
                return ResourceManager.GetString("TEST_DURATION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao tentar deletar o teste.
        /// </summary>
        public static string TEST_FAIL_DELETE {
            get {
                return ResourceManager.GetString("TEST_FAIL_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teste já existe na base de dados.
        /// </summary>
        public static string TEST_ID_EXIST {
            get {
                return ResourceManager.GetString("TEST_ID_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe teste com esse ID na base de dados.
        /// </summary>
        public static string TEST_ID_NOT_FOUND {
            get {
                return ResourceManager.GetString("TEST_ID_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O status precisa ser informado.
        /// </summary>
        public static string TEST_STATUS_EMPTY {
            get {
                return ResourceManager.GetString("TEST_STATUS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string teste {
            get {
                return ResourceManager.GetString("teste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformador deletado com sucesso.
        /// </summary>
        public static string TRANSFORMER_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("TRANSFORMER_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um transformador com esse Id cadastrado.
        /// </summary>
        public static string TRANSFORMER_EXIST {
            get {
                return ResourceManager.GetString("TRANSFORMER_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao tentar deletar o transformador.
        /// </summary>
        public static string TRANSFORMER_FAIL_DELETE {
            get {
                return ResourceManager.GetString("TRANSFORMER_FAIL_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe transformer com esse ID na base de dados.
        /// </summary>
        public static string TRANSFORMER_ID_NOT_FOUND {
            get {
                return ResourceManager.GetString("TRANSFORMER_ID_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário deletado com sucesso.
        /// </summary>
        public static string USER_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("USER_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email já existe na base de dados.
        /// </summary>
        public static string USER_EMAIL_EXIST {
            get {
                return ResourceManager.GetString("USER_EMAIL_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe usuário com esse email na base de dados.
        /// </summary>
        public static string USER_EMAIL_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_EMAIL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário com esse Id cadastrado.
        /// </summary>
        public static string USER_EXIST {
            get {
                return ResourceManager.GetString("USER_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao tentar deletar o usuário.
        /// </summary>
        public static string USER_FAIL_DELETE {
            get {
                return ResourceManager.GetString("USER_FAIL_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crendenciais do usuário inválidas. Tente novamente.
        /// </summary>
        public static string USER_FAIL_LOGIN {
            get {
                return ResourceManager.GetString("USER_FAIL_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe usuário com esse ID na base de dados.
        /// </summary>
        public static string USER_ID_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_ID_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado.
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
    }
}
